import type {Metadata} from "next";
import "./globals.css";
import Footer from "@/components/Footer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className="antialiased"
      >
        <div className="min-h-[95vh] flex flex-col relative">
          <div className="fixed inset-0 -z-10 overflow-hidden">
            <video
              autoPlay
              loop
              muted
              playsInline
              className="absolute min-w-full min-h-full object-cover"
            >
              <source src="/videos/background.mp4" type="video/mp4" />
            </video>

            <div className="absolute inset-0 bg-black/60"></div>
          </div>
          {children}

        </div>
        <Footer />
      </body>
    </html>
  );
}
